# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\dataD\ITS Camp\MATERI LJ\SEMESTER 3\Perancangan dan Integrasi Sistem\Implementasi\HMI-Lakban-Qt5-master\mainwindow_rev1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(570, 20, 201, 41))
        self.label_9.setStyleSheet("font: 75 18pt \"Arial\";\n"
"color: rgb(0, 0, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 255);")
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(30, 80, 521, 41))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 40))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";\n"
"background-color: rgb(0, 0, 131);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.gridGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.gridGroupBox.setGeometry(QtCore.QRect(30, 130, 521, 111))
        self.gridGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_daya = QtWidgets.QLabel(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_daya.sizePolicy().hasHeightForWidth())
        self.lbl_daya.setSizePolicy(sizePolicy)
        self.lbl_daya.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 30pt \"Arial\";\n"
"background-color: rgb(214, 214, 214);")
        self.lbl_daya.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_daya.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_daya.setWordWrap(False)
        self.lbl_daya.setObjectName("lbl_daya")
        self.gridLayout.addWidget(self.lbl_daya, 0, 0, 1, 1)
        self.horizontalWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalWidget1.setGeometry(QtCore.QRect(30, 20, 241, 41))
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.time_lbl = QtWidgets.QLabel(self.horizontalWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.time_lbl.setFont(font)
        self.time_lbl.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 22pt \"Arial\";")
        self.time_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.time_lbl.setObjectName("time_lbl")
        self.horizontalLayout.addWidget(self.time_lbl)
        self.label = QtWidgets.QLabel(self.horizontalWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.shift_lbl = QtWidgets.QLabel(self.horizontalWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.shift_lbl.setFont(font)
        self.shift_lbl.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 22pt \"Arial\";")
        self.shift_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.shift_lbl.setObjectName("shift_lbl")
        self.horizontalLayout.addWidget(self.shift_lbl)
        self.pb_lamp1 = QtWidgets.QPushButton(self.centralWidget)
        self.pb_lamp1.setGeometry(QtCore.QRect(570, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pb_lamp1.setFont(font)
        self.pb_lamp1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 16pt \"Arial\";")
        self.pb_lamp1.setObjectName("pb_lamp1")
        self.pb_lamp2 = QtWidgets.QPushButton(self.centralWidget)
        self.pb_lamp2.setGeometry(QtCore.QRect(570, 140, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pb_lamp2.setFont(font)
        self.pb_lamp2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 16pt \"Arial\";")
        self.pb_lamp2.setObjectName("pb_lamp2")
        # self.pb_lamp3 = QtWidgets.QPushButton(self.centralWidget)
        # self.pb_lamp3.setGeometry(QtCore.QRect(570, 200, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        # self.pb_lamp3.setFont(font)
#         self.pb_lamp3.setStyleSheet("color: rgb(255, 255, 255);\n"
# "background-color: rgb(255, 0, 0);\n"
# "font: 75 16pt \"Arial\";")
        # self.pb_lamp3.setObjectName("pb_lamp3")
        self.lamp1_indicator = QtWidgets.QLabel(self.centralWidget)
        self.lamp1_indicator.setGeometry(QtCore.QRect(720, 80, 51, 51))
        self.lamp1_indicator.setText("")
        # self.lamp1_indicator.setPixmap(QtGui.QPixmap("dark.png"))
        self.lamp1_indicator.setPixmap(QtGui.QPixmap("/home/pi/Smart-Home-Project/dark.png"))
        self.lamp1_indicator.setScaledContents(True)
        self.lamp1_indicator.setObjectName("lamp1_indicator")
        self.lamp2_indicator = QtWidgets.QLabel(self.centralWidget)
        self.lamp2_indicator.setGeometry(QtCore.QRect(720, 140, 51, 51))
        self.lamp2_indicator.setText("")
        # self.lamp2_indicator.setPixmap(QtGui.QPixmap("dark.png"))
        self.lamp1_indicator.setPixmap(QtGui.QPixmap("/home/pi/Smart-Home-Project/dark.png"))
        self.lamp2_indicator.setScaledContents(True)
        self.lamp2_indicator.setObjectName("lamp2_indicator")
        # self.lamp3_indicator = QtWidgets.QLabel(self.centralWidget)
        # self.lamp3_indicator.setGeometry(QtCore.QRect(720, 200, 51, 51))
        # self.lamp3_indicator.setText("")
        # self.lamp3_indicator.setPixmap(QtGui.QPixmap("dark.png"))
        self.lamp1_indicator.setPixmap(QtGui.QPixmap("/home/pi/Smart-Home-Project/dark.png"))
        # self.lamp3_indicator.setScaledContents(True)
        # self.lamp3_indicator.setObjectName("lamp3_indicator")
        self.pb_sources = QtWidgets.QPushButton(self.centralWidget)
        self.pb_sources.setGeometry(QtCore.QRect(570, 380, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pb_sources.setFont(font)
        self.pb_sources.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 16pt \"Arial\";")
        self.pb_sources.setObjectName("pb_sources")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalWidget_2.setGeometry(QtCore.QRect(30, 270, 521, 41))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 40))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Arial\";\n"
"background-color: rgb(0, 0, 131);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.gridGroupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.gridGroupBox_2.setGeometry(QtCore.QRect(30, 320, 521, 111))
        self.gridGroupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.gridGroupBox_2.setObjectName("gridGroupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridGroupBox_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_source = QtWidgets.QLabel(self.gridGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_source.sizePolicy().hasHeightForWidth())
        self.lbl_source.setSizePolicy(sizePolicy)
        self.lbl_source.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 30pt \"Arial\";\n"
"background-color: rgb(214, 214, 214);")
        self.lbl_source.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_source.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_source.setWordWrap(False)
        self.lbl_source.setObjectName("lbl_source")
        self.gridLayout_2.addWidget(self.lbl_source, 0, 0, 1, 1)
        self.lamp3_indicator_2 = QtWidgets.QLabel(self.centralWidget)
        self.lamp3_indicator_2.setGeometry(QtCore.QRect(720, 380, 51, 51))
        self.lamp3_indicator_2.setText("")
        # self.lamp3_indicator_2.setPixmap(QtGui.QPixmap("source.png"))
        self.lamp3_indicator_2.setPixmap(QtGui.QPixmap("/home/pi/Smart-Home-Project/source.png"))
        self.lamp3_indicator_2.setScaledContents(True)
        self.lamp3_indicator_2.setObjectName("lamp3_indicator_2")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Lamp Switch"))
        self.label_10.setText(_translate("MainWindow", "Total Daya (Watt)"))
        self.lbl_daya.setText(_translate("MainWindow", "0"))
        self.time_lbl.setText(_translate("MainWindow", "09:45:55"))
        self.label.setText(_translate("MainWindow", "|"))
        self.shift_lbl.setText(_translate("MainWindow", "Home"))
        self.pb_lamp1.setText(_translate("MainWindow", "Lamp 1"))
        self.pb_lamp2.setText(_translate("MainWindow", "Lamp 2"))
        # self.pb_lamp3.setText(_translate("MainWindow", "Lamp 3"))
        self.pb_sources.setText(_translate("MainWindow", "Source"))
        self.label_11.setText(_translate("MainWindow", "Sumber Listrik"))
        self.lbl_source.setText(_translate("MainWindow", "PLN"))

